create table link
(
    id integer primary key generated by default as identity,
    url varchar not null unique,
    updated_at timestamp with time zone not null
);
create table chat
(
    chat_id integer primary key
);
create table connections
(
    chat_id integer references chat(chat_id),
    link_id integer references link(id),
    primary key (chat_id, link_id)
)

