create table link
(
    id bigint primary key generated by default as identity,
    url varchar not null unique,
    updated_at timestamp with time zone not null
);
create table chat
(
    chat_id bigint primary key
);
create table connections
(
    chat_id bigint references chat(chat_id),
    link_id bigint references link(id),
    primary key (chat_id, link_id)
)

