global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scrapper'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['scrapper:8081']
  - job_name: 'bot'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'bot:8091' ]
