app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    seconds-threshold: 30

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:6543/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  github-client-config:
    base-url: ${GITHUB_BASE_URL:https://api.github.com}
  so-client-config:
    base-url: ${SO_BASE_URL:https://api.stackexchange.com}
  bot-client-config:
    base-url: ${BOT_BASE_URL:http://localhost:8090}
