app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
    seconds-threshold: 30 #seconds
  database-access-type: jpa
  use-queue: true
  kafka-topic-name: updates_main

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:6543/scrapper
    username: ${DB_USERNAME:postgres}
    password: postgres
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: false
  jooq:
    sql-dialect: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  github-client-properties:
    base-url: ${GITHUB_BASE_URL:https://api.github.com}
    retry-attempts: ${GITHUB_RETRY_ATTEMPTS:4}
    retry-duration: ${GITHUB_RETRY_DURATION:2} #seconds
    retry-policy: ${GITHUB_RETRY_POLICY:constant} #values: linear, exponential, constant
    retry-codes:
      - 404
  so-client-properties:
    base-url: ${SO_BASE_URL:https://api.stackexchange.com}
    retry-attempts: ${SO_RETRY_ATTEMPTS:3}
    retry-duration: ${SO_RETRY_DURATION:2} #seconds
    retry-policy: ${SO_RETRY_POLICY:constant} #values: linear, exponential, constant
    retry-codes:
      - 404
  bot-client-properties:
    base-url: ${BOT_BASE_URL:http://localhost:8090}
    retry-attempts: ${BOT_RETRY_ATTEMPTS:3}
    retry-duration: ${BOT_RETRY_DURATION:2} #seconds
    retry-policy: ${BOT_RETRY_POLICY:constant} #values: linear, exponential, constant
    retry-codes:
      - 404

bucket:
  refill-size: 5
  refill-interval: 1 #minutes
  capacity: 5

bucket-cache:
  max-size: 100
  expiration-time: 10 #minutes

kafka:
  producer:
    bootstrap-servers: http://localhost:9092
    client-id: bot
    acks-mode: 0
    delivery-timeout: 60s
    linger-ms: 1_000
    batch-size: 100_000

