app:
  telegram-token: ${BOT_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  scrapper-client-properties:
    base-url: ${SCRAPPER_BASE_URL:http://localhost:8080}
    retry-attempts: ${SCRAPPER_RETRY_ATTEMPTS:4}
    retry-duration: ${SCRAPPER_RETRY_DURATION:2} #seconds
    retry-policy: ${SCRAPPER_RETRY_POLICY:constant} #values: linear, exponential, constant
    retry-codes:
      - 404

bucket:
  refill-size: 5
  refill-interval: 1 #minutes
  capacity: 5

bucket-cache:
  max-size: 100
  expiration-time: 10 #minutes
