app:
  telegram-token: ${BOT_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  scrapper-client-config:
    base-url: ${SCRAPPER_BASE_URL:http://localhost:8080}
