app:
  telegram-token: ${BOT_API_KEY}
  kafka-topic-name: updates_main

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

web-clients:
  scrapper-client-properties:
    base-url: ${SCRAPPER_BASE_URL:http://localhost:8080}
    retry-attempts: ${SCRAPPER_RETRY_ATTEMPTS:4}
    retry-duration: ${SCRAPPER_RETRY_DURATION:2} #seconds
    retry-policy: ${SCRAPPER_RETRY_POLICY:constant} #values: linear, exponential, constant
    retry-codes:
      - 404

bucket:
  refill-size: 5
  refill-interval: 1 #minutes
  capacity: 5

bucket-cache:
  max-size: 100
  expiration-time: 10 #minutes

kafka:
  consumer:
    bootstrap-servers: kafka1:9092
    group-id: bot
    auto-offset-reset: earliest
    max-poll-interval-ms: 300_000
    enable-auto-commit: false
    concurrency: 1
  producer:
    bootstrap-servers: kafka1:9092
    client-id: bot
    acks-mode: 0
    delivery-timeout: 60s
    linger-ms: 1_000
    batch-size: 100_000

management:
  server:
    port: 8091
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

